// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_NAXKYELaxihHP4Ap_BXKuLOG6LErP4Y',
    appId: '1:511510870696:web:aedaba4b659bc22477e09d',
    messagingSenderId: '511510870696',
    projectId: 'attendance-app-824c2',
    authDomain: 'attendance-app-824c2.firebaseapp.com',
    storageBucket: 'attendance-app-824c2.appspot.com',
    measurementId: 'G-HVJ0XD5G9F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRbHjBZyWxEx4YEi_ivCCirfbXi68rN1w',
    appId: '1:511510870696:android:7c78a65aa3bd9dc077e09d',
    messagingSenderId: '511510870696',
    projectId: 'attendance-app-824c2',
    storageBucket: 'attendance-app-824c2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpCnNBZsu49cTamwc6a3wonXX5XkUQD5E',
    appId: '1:511510870696:ios:0df8c7d678de699277e09d',
    messagingSenderId: '511510870696',
    projectId: 'attendance-app-824c2',
    storageBucket: 'attendance-app-824c2.appspot.com',
    iosClientId: '511510870696-3jh8opaekdbms2hfks8rcb40rtd0dvbs.apps.googleusercontent.com',
    iosBundleId: 'com.example.attendanceApp',
  );
}
